/* Generated by genconfig */
unsigned int width; // display width
unsigned int height; // display height
unsigned int mirc_colour_compat; // mirc colour compatibility
unsigned int force_redraw; // force-redraw
unsigned int buflines; // buffer lines
unsigned int maxnlen; // max nick length
bool full_width_colour; // full width colour
bool hilite_tabstrip; // highlight tabstrip
bool tsb; // top status bar
unsigned int tping; // outbound ping time
unsigned int ts; // timestamping
bool utc; // UTC timestamps
bool its; // input clock
bool quiet; // quiet mode
bool debug; // debugging
bool conf; // conference mode (default)
bool titles; // xterm title
