/* Generated by genconfig */
	width=80;
	height=24;
	mirc_colour_compat=1;
	force_redraw=2;
	buflines=256;
	maxnlen=16;
	full_width_colour=-1;
	hilite_tabstrip=-1;
	tsb=-1;
	tping=30;
	ts=1;
	utc=-1;
