#!/usr/bin/python
# gen_numerics_text.py: generate numeric_text.c

import numerics

print """/*
	quIRC - simple terminal-based IRC client
	Copyright (C) 2010-13 Edward Cree

	See quirc.c for license information
	numeric_text: names of IRC numeric replies
*/

/***
	This file is generated by gen_numerics_text.py from masters in numerics.py
	Do not make edits directly to this file!  Edit the masters instead.
***/

#include <stdlib.h> // for NULL

const char *numeric_names[1000]={"""
for i in xrange(1000):
	if i in numerics.nums:
		print '"'+numerics.nums[i].getname()+'",'
	else:
		print 'NULL,'
print '};'
