#!/usr/bin/python
# numerics.py: authoritative version of the numerics list

class NumericMessage(object):
	def __init__(self, name, num, comment, x):
		self.name    = name
		self.num     = num
		self.comment = comment
		self.x       = x
		self.typ     = 'NUM'
	def getname(self):
		return self.typ+'_'+('X_' if self.x else '')+self.name
	@classmethod
	def justify(cls, s):
		l=int(len(s)/4)
		return s+'\t'*(5-l)
	def __str__(self):
		return '#define\t%s\t%03d\t// %s' % (self.justify(self.getname()), self.num, self.comment)

class NumericError(NumericMessage):
	def __init__(self, *args):
		super(NumericError, self).__init__(*args)
		self.typ = 'ERR'

class NumericReply(NumericMessage):
	def __init__(self, *args):
		super(NumericReply, self).__init__(*args)
		self.typ = 'RPL'

nums={}
def add(n):
	nums[n.num] = n
add(NumericError('NOSUCHNICK', 401, '"<nickname> :No such nick/channel"\tUsed to indicate the nickname parameter supplied to a command is currently unused.', 0))
add(NumericError('NOSUCHSERVER', 402, '"<server name> :No such server"\tUsed to indicate the server name given currently doesn\'t exist.', 0))
add(NumericError('NOSUCHCHANNEL', 403, '"<channel name> :No such channel"\tUsed to indicate the given channel name is invalid.', 0))
add(NumericError('CANNOTSENDTOCHAN', 404, '"<channel name> :Cannot send to channel"\tSent to a user who is either (a) not on a channel which is mode +n or (b) not a chanop (or mode +v) on a channel which has mode +m set and is trying to send a PRIVMSG message to that channel.', 0))
add(NumericError('TOOMANYCHANNELS', 405, '"<channel name> :You have joined too many channels"\tSent to a user when they have joined the maximum number of allowed channels and they try to join another channel.', 0))
add(NumericError('WASNOSUCHNICK', 406, '"<nickname> :There was no such nickname"\tReturned by WHOWAS to indicate there is no history information for that nickname.', 0))
add(NumericError('TOOMANYTARGETS', 407, '"<target> :Duplicate recipients. No message delivered"\tReturned to a client which is attempting to send PRIVMSG/NOTICE using the user@host destination format and for a user@host which has several occurrences.', 0))
add(NumericError('NOORIGIN', 409, '":No origin specified"\tPING or PONG message missing the originator parameter which is required since these commands must work without valid prefixes.', 0))
add(NumericError('NORECIPIENT', 411, '":No recipient given (<command>)"', 0))
add(NumericError('NOTEXTTOSEND', 412, '":No text to send"', 0))
add(NumericError('NOTOPLEVEL', 413, '"<mask> :No toplevel domain specified"', 0))
add(NumericError('WILDTOPLEVEL', 414, '"<mask> :Wildcard in toplevel domain"\t412 - 414 are returned by PRIVMSG to indicate that the message wasn\'t delivered for some reason. ERR_NOTOPLEVEL and ERR_WILDTOPLEVEL are errors that are returned when an invalid use of "PRIVMSG $<server>" or "PRIVMSG #<host>" is attempted.', 0))
add(NumericError('UNKNOWNCOMMAND', 421, '"<command> :Unknown command"\tReturned to a registered client to indicate that the command sent is unknown by the server.', 0))
add(NumericError('NOMOTD', 422, '":MOTD File is missing"\tServer\'s MOTD file could not be opened by the server.', 0))
add(NumericError('NOADMININFO', 423, '"<server> :No administrative info available"\tReturned by a server in response to an ADMIN message when there is an error in finding the appropriate information.', 0))
add(NumericError('FILEERROR', 424, '":File error doing <file op> on <file>"\tGeneric error message used to report a failed file operation during the processing of a message.', 0))
add(NumericError('NONICKNAMEGIVEN', 431, '":No nickname given"\tReturned when a nickname parameter expected for a command and isn\'t found.', 0))
add(NumericError('ERRONEOUSNICKNAME', 432, '"<nick> :Erroneous nickname"\tReturned after receiving a NICK message which contains characters which do not fall in the defined set. See section x.x.x for details on valid nicknames.', 0))
add(NumericError('NICKNAMEINUSE', 433, '"<nick> :Nickname is already in use"\tReturned when a NICK message is processed that results in an attempt to change to a currently existing nickname.', 0))
add(NumericError('NICKCOLLISION', 436, '"<nick> :Nickname collision KILL"\tReturned by a server to a client when it detects a nickname collision (registered of a NICK that already exists by another server).', 0))
add(NumericError('USERNOTINCHANNEL', 441, '"<nick> <channel> :They aren\'t on that channel"\tReturned by the server to indicate that the target user of the command is not on the given channel.', 0))
add(NumericError('NOTONCHANNEL', 442, '"<channel> :You\'re not on that channel"\tReturned by the server whenever a client tries to perform a channel effecting command for which the client isn\'t a member.', 0))
add(NumericError('USERONCHANNEL', 443, '"<user> <channel> :is already on channel"\tReturned when a client tries to invite a user to a channel they are already on.', 0))
add(NumericError('NOLOGIN', 444, '"<user> :User not logged in"\tReturned by the summon after a SUMMON command for a user was unable to be performed since they were not logged in.', 0))
add(NumericError('SUMMONDISABLED', 445, '":SUMMON has been disabled"\tReturned as a response to the SUMMON command. Must be returned by any server which does not implement it.', 0))
add(NumericError('USERSDISABLED', 446, '":USERS has been disabled"\tReturned as a response to the USERS command. Must be returned by any server which does not implement it.', 0))
add(NumericError('NOTREGISTERED', 451, '":You have not registered"\tReturned by the server to indicate that the client must be registered before the server will allow it to be parsed in detail.', 0))
add(NumericError('NEEDMOREPARAMS', 461, '"<command> :Not enough parameters"\tReturned by the server by numerous commands to indicate to the client that it didn\'t supply enough parameters.', 0))
add(NumericError('ALREADYREGISTRED', 462, '":You may not reregister"\tReturned by the server to any link which tries to change part of the registered details (such as password or user details from second USER message).', 0))
add(NumericError('NOPERMFORHOST', 463, '":Your host isn\'t among the privileged"\tReturned to a client which attempts to register with a server which does not been setup to allow connections from the host the attempted connection is tried.', 0))
add(NumericError('PASSWDMISMATCH', 464, '":Password incorrect"\tReturned to indicate a failed attempt at registering a connection for which a password was required and was either not given or incorrect.', 0))
add(NumericError('YOUREBANNEDCREEP', 465, '":You are banned from this server"\tReturned after an attempt to connect and register yourself with a server which has been setup to explicitly deny connections to you.', 0))
add(NumericError('KEYSET', 467, '"<channel> :Channel key already set"', 0))
add(NumericError('CHANNELISFULL', 471, '"<channel> :Cannot join channel (+l)"', 0))
add(NumericError('UNKNOWNMODE', 472, '"<char> :is unknown mode char to me"', 0))
add(NumericError('INVITEONLYCHAN', 473, '"<channel> :Cannot join channel (+i)"', 0))
add(NumericError('BANNEDFROMCHAN', 474, '"<channel> :Cannot join channel (+b)"', 0))
add(NumericError('BADCHANNELKEY', 475, '"<channel> :Cannot join channel (+k)"', 0))
add(NumericError('NOPRIVILEGES', 481, '":Permission Denied- You\'re not an IRC operator"\tAny command requiring operator privileges to operate must return this error to indicate the attempt was unsuccessful.', 0))
add(NumericError('CHANOPRIVSNEEDED', 482, '"<channel> :You\'re not channel operator"\tAny command requiring \'chanop\' privileges (such as MODE messages) must return this error if the client making the attempt is not a chanop on the specified channel.', 0))
add(NumericError('CANTKILLSERVER', 483, '":You cant kill a server!"\tAny attempts to use the KILL command on a server are to be refused and this error returned directly to the client.', 0))
add(NumericError('NOOPERHOST', 491, '":No O-lines for your host"\tIf a client sends an OPER message and the server has not been configured to allow connections from the client\'s host as an operator, this error must be returned.', 0))
add(NumericError('UMODEUNKNOWNFLAG', 501, '":Unknown MODE flag"\tReturned by the server to indicate that a MODE message was sent with a nickname parameter and that the a mode flag sent was not recognized.', 0))
add(NumericError('USERSDONTMATCH', 502, '":Cant change mode for other users"\tError sent to any user trying to view or change the user mode for a user other than themselves.', 0))
add(NumericReply('ISUPPORT', 5, 'http://www.irc.org/tech_docs/draft-brocklesby-irc-isupport-03.txt', 1))
add(NumericReply('NONE', 300, 'Dummy reply number. Not used.', 0))
add(NumericReply('USERHOST', 302, '":[<reply>{<space><reply>}]"\tReply format used by USERHOST to list replies to the query list. The reply string is composed as follows:\t<reply> ::= <nick>[\'*\'] \'=\' <\'+\'|\'-\'><hostname>\tThe \'*\' indicates whether the client has registered as an Operator. The \'-\' or \'+\' characters represent whether the client has set an AWAY message or not respectively.', 0))
add(NumericReply('ISON', 303, '":[<nick> {<space><nick>}]"\tReply format used by ISON to list replies to the query list.', 0))
add(NumericReply('AWAY', 301, '"<nick> :<away message>"', 0))
add(NumericReply('UNAWAY', 305, '":You are no longer marked as being away"', 0))
add(NumericReply('NOWAWAY', 306, '":You have been marked as being away"\tThese replies are used with the AWAY command (if allowed). RPL_AWAY is sent to any client sending a PRIVMSG to a client which is away. RPL_AWAY is only sent by the server to which the client is connected. Replies RPL_UNAWAY and RPL_NOWAWAY are sent when the client removes and sets an AWAY message.', 0))
add(NumericReply('WHOISUSER', 311, '"<nick> <user> <host> * :<real name>"', 0))
add(NumericReply('WHOISSERVER', 312, '"<nick> <server> :<server info>"', 0))
add(NumericReply('WHOISOPERATOR', 313, '"<nick> :is an IRC operator"', 0))
add(NumericReply('WHOISIDLE', 317, '"<nick> <integer> :seconds idle"', 0))
add(NumericReply('ENDOFWHOIS', 318, '"<nick> :End of /WHOIS list"', 0))
add(NumericReply('WHOISCHANNELS', 319, '"<nick> :{[@|+]<channel><space>}"\tReplies 311 - 313, 317 - 319 are all replies generated in response to a WHOIS message. Given that there are enough parameters present, the answering server must either formulate a reply out of the above numerics (if the query nick is found) or return an error reply. The \'*\' in RPL_WHOISUSER is there as the literal character and not as a wild card. For each reply set, only RPL_WHOISCHANNELS may appear more than once (for long lists of channel names). The \'@\' and \'+\' characters next to the channel name indicate whether a client is a channel operator or has been granted permission to speak on a moderated channel. The RPL_ENDOFWHOIS reply is used to mark the end of processing a WHOIS message.', 0))
add(NumericReply('WHOWASUSER', 314, '"<nick> <user> <host> * :<real name>"', 0))
add(NumericReply('ENDOFWHOWAS', 369, '"<nick> :End of WHOWAS"\tWhen replying to a WHOWAS message, a server must use the replies RPL_WHOWASUSER, RPL_WHOISSERVER or ERR_WASNOSUCHNICK for each nickname in the presented list. At the end of all reply batches, there must be RPL_ENDOFWHOWAS (even if there was only one reply and it was an error).', 0))
add(NumericReply('LISTSTART', 321, '"Channel :Users Name"', 0))
add(NumericReply('LIST', 322, '"<channel> <# visible> :<topic>"', 0))
add(NumericReply('LISTEND', 323, '":End of /LIST"\tReplies RPL_LISTSTART, RPL_LIST, RPL_LISTEND mark the start, actual replies with data and end of the server\'s response to a LIST command. If there are no channels available to return, only the start and end reply must be sent.', 0))
add(NumericReply('CHANNELMODEIS', 324, '"<channel> <mode> <mode params>"', 0))
add(NumericReply('NOTOPIC', 331, '"<channel> :No topic is set"', 0))
add(NumericReply('TOPIC', 332, '"<channel> :<topic>"\tWhen sending a TOPIC message to determine the channel topic, one of two replies is sent. If the topic is set, RPL_TOPIC is sent back else RPL_NOTOPIC.', 0))
add(NumericReply('TOPICWASSET', 333, '"<channel> <nick> <time>" Indicates who set the TOPIC, and when.  Not normative.', 1))
add(NumericReply('INVITING', 341, '"<channel> <nick>"\tReturned by the server to indicate that the attempted INVITE message was successful and is being passed onto the end client.', 0))
add(NumericReply('SUMMONING', 342, '"<user> :Summoning user to IRC"\tReturned by a server answering a SUMMON message to indicate that it is summoning that user.', 0))
add(NumericReply('VERSION', 351, '"<version>.<debuglevel> <server> :<comments>"\tReply by the server showing its version details. The <version> is the version of the software being used (including any patchlevel revisions) and the <debuglevel> is used to indicate if the server is running in "debug mode".  The "comments" field may contain any comments about the version or further version details.', 0))
add(NumericReply('WHOREPLY', 352, '"<channel> <user> <host> <server> <nick> <H|G>[*][@|+] :<hopcount> <real name>"', 0))
add(NumericReply('ENDOFWHO', 315, '"<name> :End of /WHO list"\tThe RPL_WHOREPLY and RPL_ENDOFWHO pair are used to answer a WHO message. The RPL_WHOREPLY is only sent if there is an appropriate match to the WHO query. If there is a list of parameters supplied with a WHO message, a RPL_ENDOFWHO must be sent after processing each list item with <name> being the item.', 0))
add(NumericReply('NAMREPLY', 353, '"<channel> :[[@|+]<nick> [[@|+]<nick> [...]]]"', 0))
add(NumericReply('ENDOFNAMES', 366, '"<channel> :End of /NAMES list"\tTo reply to a NAMES message, a reply pair consisting of RPL_NAMREPLY and RPL_ENDOFNAMES is sent by the server back to the client. If there is no channel found as in the query, then only RPL_ENDOFNAMES is returned. The exception to this is when a NAMES message is sent with no parameters and all visible channels and contents are sent back in a series of RPL_NAMEREPLY messages with a RPL_ENDOFNAMES to mark the end.', 0))
add(NumericReply('LINKS', 364, '"<mask> <server> :<hopcount> <server info>"', 0))
add(NumericReply('ENDOFLINKS', 365, '"<mask> :End of /LINKS list"\tIn replying to the LINKS message, a server must send replies back using the RPL_LINKS numeric and mark the end of the list using an RPL_ENDOFLINKS reply.v ', 0))
add(NumericReply('BANLIST', 367, '"<channel> <banid>"', 0))
add(NumericReply('ENDOFBANLIST', 368, '"<channel> :End of channel ban list"\tWhen listing the active \'bans\' for a given channel, a server is required to send the list back using the RPL_BANLIST and RPL_ENDOFBANLIST messages. A separate RPL_BANLIST is sent for each active banid. After the banids have been listed (or if none present) a RPL_ENDOFBANLIST must be sent.', 0))
add(NumericReply('INFO', 371, '":<string>"', 0))
add(NumericReply('ENDOFINFO', 374, '":End of /INFO list"\tA server responding to an INFO message is required to send all its \'info\' in a series of RPL_INFO messages with a RPL_ENDOFINFO reply to indicate the end of the replies.', 0))
add(NumericReply('MOTDSTART', 375, '":- <server> Message of the day - "', 0))
add(NumericReply('MOTD', 372, '":- <text>"', 0))
add(NumericReply('ENDOFMOTD', 376, '":End of /MOTD command"\tWhen responding to the MOTD message and the MOTD file is found, the file is displayed line by line, with each line no longer than 80 characters, using RPL_MOTD format replies. These should be surrounded by a RPL_MOTDSTART (before the\tRPL_MOTDs) and an RPL_ENDOFMOTD (after).', 0))
add(NumericReply('YOUREOPER', 381, '":You are now an IRC operator"\tRPL_YOUREOPER is sent back to a client which has just successfully issued an OPER message and gained operator status.', 0))
add(NumericReply('REHASHING', 382, '"<config file> :Rehashing"\tIf the REHASH option is used and an operator sends a REHASH message, an RPL_REHASHING is sent back to the operator.', 0))
add(NumericReply('TIME', 391, '"<server> :<string showing server\'s local time>"\tWhen replying to the TIME message, a server must send the reply using the RPL_TIME format above. The string showing the time need only contain the correct day and time there. There is no further requirement for the time string.', 0))
add(NumericReply('USERSSTART', 392, '":UserID Terminal Host"', 0))
add(NumericReply('USERS', 393, '":%-8s %-9s %-8s"', 0))
add(NumericReply('ENDOFUSERS', 394, '":End of users"', 0))
add(NumericReply('NOUSERS', 395, '":Nobody logged in"\tIf the USERS message is handled by a server, the replies RPL_USERSTART, RPL_USERS, RPL_ENDOFUSERS and RPL_NOUSERS are used. RPL_USERSSTART must be sent first, following by either a sequence of RPL_USERS or a single RPL_NOUSER. Following this is RPL_ENDOFUSERS.', 0))
add(NumericReply('TRACELINK', 200, '"Link <version & debug level> <destination> <next server>"', 0))
add(NumericReply('TRACECONNECTING', 201, '"Try. <class> <server>"', 0))
add(NumericReply('TRACEHANDSHAKE', 202, '"H.S. <class> <server>"', 0))
add(NumericReply('TRACEUNKNOWN', 203, '"???? <class> [<client IP address in dot form>]"', 0))
add(NumericReply('TRACEOPERATOR', 204, '"Oper <class> <nick>"', 0))
add(NumericReply('TRACEUSER', 205, '"User <class> <nick>"', 0))
add(NumericReply('TRACESERVER', 206, '"Serv <class> <int>S <int>C <server> <nick!user|*!*>@<host|server>"', 0))
add(NumericReply('TRACENEWTYPE', 208, '"<newtype> 0 <client name>"', 0))
add(NumericReply('TRACELOG', 261, '"File <logfile> <debug level>"\tThe RPL_TRACE* are all returned by the server in response to the TRACE message. How many are returned is dependent on the the TRACE message and whether it was sent by an operator or not. There is no predefined order for which occurs first. Replies RPL_TRACEUNKNOWN, RPL_TRACECONNECTING and RPL_TRACEHANDSHAKE are all used for connections which have not been fully established and are either unknown, still attempting to connect or in the process of completing the \'server handshake\'. RPL_TRACELINK is sent by any server which handles a TRACE message and has to pass it on to another server. The list of RPL_TRACELINKs sent in response to a TRACE command traversing the IRC network should reflect the actual connectivity of the servers themselves along that path. RPL_TRACENEWTYPE is to be used for any connection which does not fit in the other categories but is being displayed anyway.', 0))
add(NumericReply('STATSLINKINFO', 211, '"<linkname> <sendq> <sent messages> <sent bytes> <received messages> <received bytes> <time open>"', 0))
add(NumericReply('STATSCOMMANDS', 212, '"<command> <count>"', 0))
add(NumericReply('STATSCLINE', 213, '"C <host> * <name> <port> <class>"', 0))
add(NumericReply('STATSNLINE', 214, '"N <host> * <name> <port> <class>"', 0))
add(NumericReply('STATSILINE', 215, '"I <host> * <host> <port> <class>"', 0))
add(NumericReply('STATSKLINE', 216, '"K <host> * <username> <port> <class>"', 0))
add(NumericReply('STATSYLINE', 218, '"Y <class> <ping frequency> <connect frequency> <max sendq>"', 0))
add(NumericReply('ENDOFSTATS', 219, '"<stats letter> :End of /STATS report"', 0))
add(NumericReply('STATSLLINE', 241, '"L <hostmask> * <servername> <maxdepth>"', 0))
add(NumericReply('STATSUPTIME', 242, '":Server Up %d days %d:%02d:%02d"', 0))
add(NumericReply('STATSOLINE', 243, '"O <hostmask> * <name>"', 0))
add(NumericReply('STATSHLINE', 244, '"H <hostmask> * <servername>"', 0))
add(NumericReply('UMODEIS', 221, '"<user mode string>"\tTo answer a query about a client\'s own mode, RPL_UMODEIS is sent back.', 0))
add(NumericReply('LUSERCLIENT', 251, '":There are <integer> users and <integer> invisible on <integer> servers"', 0))
add(NumericReply('LUSEROP', 252, '"<integer> :operator(s) online"', 0))
add(NumericReply('LUSERUNKNOWN', 253, '"<integer> :unknown connection(s)"', 0))
add(NumericReply('LUSERCHANNELS', 254, '"<integer> :channels formed"', 0))
add(NumericReply('LUSERME', 255, '":I have <integer> clients and <integer> servers"\tIn processing an LUSERS message, the server sends a set of replies from RPL_LUSERCLIENT, RPL_LUSEROP, RPL_LUSERUNKNOWN, RPL_LUSERCHANNELS and RPL_LUSERME. When replying, a server must send back RPL_LUSERCLIENT and RPL_LUSERME. The other replies are only sent back if a non-zero count is found for them.', 0))
add(NumericReply('ADMINME', 256, '"<server> :Administrative info"', 0))
add(NumericReply('ADMINLOC1', 257, '":<admin info>"', 0))
add(NumericReply('ADMINLOC2', 258, '":<admin info>"', 0))
add(NumericReply('ADMINEMAIL', 259, '":<admin info>"\tWhen replying to an ADMIN message, a server is expected to use replies RLP_ADMINME through to RPL_ADMINEMAIL and provide a text message with each. For RPL_ADMINLOC1 a description of what city, state and country the server is in is expected, followed by details of the university and department (RPL_ADMINLOC2) and finally the administrative contact for the server (an email address here is required) in RPL_ADMINEMAIL.', 0))
add(NumericReply('LOCALUSERS', 265, '":Current Local Users: <integer>\\tMax: <integer>"  Appears to count the users connected directly to the server.  Non-normative.', 1))
add(NumericReply('GLOBALUSERS', 266, '":Current Global Users: <integer>\\tMax: <integer>"  Appears to count the users connected to the network.  Non-normative.', 1))
